### ISSUE TITLE
Bug: Button to open window doesn't work

### ISSUE THREAD

**Issue by ManOrMonster** [javsezlol1/Stylez#12]
After updating to latest commit [b8df22e](https://github.com/javsezlol1/Stylez/commit/b8df22e3e6bcb17aa3d3c7f1c0dc233e3dd69df3), the Stylez button will not open the window.

<img width="254" alt="image" src="https://github.com/javsezlol1/Stylez/assets/3925151/96c493ef-f274-45cb-8c8b-df615671ca6c">

Terminal log error:

```
*** Error loading script: Stylez.py
    Traceback (most recent call last):
      File "C:\stable-diffusion\automatic1111\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\stable-diffusion\automatic1111\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\stable-diffusion\automatic1111\extensions\Stylez\scripts\Stylez.py", line 44, in <module>
        data = json.load(json_file)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
        return loads(fp.read(),
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 1 (char 75)
```

I took a look at config.json and it contained invalid JSON:

<img width="300" alt="image" src="https://github.com/javsezlol1/Stylez/assets/3925151/bdc2fd57-ff61-4243-a162-9503b29e4dc4">

I corrected the JSON and it now works for me. Heads up that others might have experienced this too for some reason.

**Comment by javsezlol1** [comment]
weird. i had an issue earlier wher github wasnt uploading my files correctly maybe this caused it

**Comment by javsezlol1** [comment]
ill close this for now let me know if you have this issue again
