### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by hotwareboy** [javsezlol1/Stylez#22]
Error on launch; currently using automatic1111 dev branch.

*** Error loading script: Stylez.py
    Traceback (most recent call last):
      File "C:\automatic1111\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\automatic1111\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\automatic1111\extensions\Stylez\scripts\Stylez.py", line 148, in <module>
        if os.path.exists(shared.cmd_opts.styles_file):
      File "C:\python_3_10\lib\genericpath.py", line 19, in exists
        os.stat(path)
    TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

**Comment by javsezlol1** [comment]
not sure what the issue is there or if something has changed in SD dev branch. i dont want to make any changes to the extension incase its a bug or something that wont make the final build. 

you can do the following to work around it though
head to your sd folder >extensions > Stylez > scripts > edit config.json
set     "autoconvert" to false
