### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by Adzido** [javsezlol1/Stylez#4]
Civitai Helper: Get Custom Model Folder
*** Error loading script: Stylez.py
    Traceback (most recent call last):
      File "C:\Users\sdhserh\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\sdhserh\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\sdhserh\stable-diffusion-webui\extensions\Stylez\scripts\Stylez.py", line 98, in <module>
        save_json_objects(json_objects)
      File "C:\Users\sdhserh\stable-diffusion-webui\extensions\Stylez\scripts\Stylez.py", line 89, in save_json_objects
        with open(json_file_path, 'w') as jsonfile:
    OSError: [Errno 22] Invalid argument: 'extensions\\Stylez\\styles\\CSVConversion\\____*Negative Prompts Only____.json'
    
    
Any idea? I thought it was a different extension, I've tried disabling all but one and the error still occurs. 
On the new SD instance (reinstalled) it works but still needs help because it has to work on the one where I have all the plugins, models etc.

**Comment by Adzido** [comment]
Its still the same. I mean there is not error but its still not working, when I click on icon (to use it) nothing happend... :(

**Comment by javsezlol1** [comment]
could you please try again on the latest version this should of been fixed. if not could you upload your csv file and send it me a link so i can test

**Comment by javsezlol1** [comment]
> Its still the same. I mean there is not error but its still not working, when I click on icon (to use it) nothing happend... :(

did you update ?

**Comment by Adzido** [comment]
Its working now, its not about update its about that - ur addon not working with mov2mov plugin to A1111.
